### ISSUE TITLE
Update Layer for Compatibility with MITRE ATT&CK Navigator 5.0.0

### ISSUE THREAD

**Issue by A-Pisani** [facebookresearch/privacy_adversarial_framework#3]
### Description
Hello,

I encountered an issue when attempting to open the provided layer file (`paf_navigator.json`) in the current version of the MITRE ATT&CK Navigator.
![image](https://github.com/facebookresearch/privacy_adversarial_framework/assets/48137513/305f689c-cca9-4df1-9c72-9f0e4a705564)

**Comment by stevenh6696** [comment]
@A-Pisani I believe you're encountering this issue while trying to open an existing layer (under `Open Existing Layer`). The correct path is to create a new layer (`Create New Layer` -> `More Options` -> `Collection or STIX bundle URL = https://raw.githubusercontent.com/facebookresearch/privacy_adversarial_framework/main/paf_navigator.json` -> `Bundle version number = 1` -> `Bundle domain = PAF`)

Just tried this on the [ATT&CK Navigator site](https://mitre-attack.github.io/attack-navigator/)
